[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "riemann"
version = "0.1.0"
description = "Technical PDF reader for Linux"
requires-python = ">=3.11"
dependencies = [
    "PySide6>=6.5",
]

[tool.maturin]
# This points to the Rust crate
manifest-path = "rust-core/Cargo.toml"
# This tells maturin that the python code is inside python-app/riemann
python-source = "python-app"
# The name of the compiled .so module
module-name = "riemann_core"